---
# tasks file for swarmworker

- name: Add Workers to the Swarm
  shell: docker swarm join --token {{ hostvars['swarm-master']['worker_token']['stdout'] }} {{ hostvars['swarm-master']['ansible_default_ipv4']['address'] }}:2377
