version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
  front-end:
    container_name: front-end
    image: front-end:latest
    build: ./front-end
    environment:
      PASSWORD: ${password}
  name-api:
    container_name: name_api
    image: name-api:latest
    build: ./name-api
  unit-api:
    container_name: unit_api
    image: unit-api:latest
    build: ./unit-api
  effect-api:
    container_name: effect_api
    image: effect-api:latest
    build: ./effect-api
  db:
    container_name: eventsdb
    image: eventsdb:latest
    build: ./events-db
    environment:
      MYSQL_ROOT_PASSWORD: ${password}
