version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - "front-end"
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
  front-end:
    container_name: front-end
    image: front-end:latest
    build: ./front-end
    depends_on:
      - "eventsdb"
    environment:
      PASSWORD: ${MYSQL_ROOT_PASSWORD}
  name-api:
    container_name: name-api
    image: name-api:latest
    build: ./name-api
  unit-api:
    container_name: unit-api
    image: unit-api:latest
    build: ./unit-api
  effect-api:
    container_name: effect-api
    image: effect-api:latest
    build: ./effect-api
  eventsdb:
    container_name: eventsdb
    image: eventsdb:latest
    build: ./events-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
