version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
  front-end:
    container_name: front-end
    image: agray998/front-end:latest
    build: ./front-end
    environment:
      DB_URI: ${DB_URI}
  name-api:
    container_name: name-api
    image: agray998/name-api:latest
    build: ./name-api
  unit-api:
    container_name: unit-api
    image: agray998/unit-api:latest
    build: ./unit-api
  effect-api:
    container_name: effect-api
    image: agray998/effect-api:latest
    build: ./effect-api
  eventsdb:
    container_name: eventsdb
    image: agray998/eventsdb:latest
    build: ./events-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
