apiVersion: v1
kind: Service
metadata:
  name: name-api
  spec:
    selector:
      app: name-api
    ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-api
  labels:
    app: name-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: name-api
    spec:
      containers:
      - name: name-api
        image: agray998/name-api:latest
        ports:
        - containerPort: 5000
